src/core/urls.py
from django.conf.urls import url

from .views import (
    WordsAddView, WordsReviewView, WordsEditView, WordsApproveView,
    StudentsAddView,SuccessView, HomeView
)


app_name = 'core'

urlpatterns = [
    url(r'^review/', WordsReviewView.as_view(), name='words_review'),
    url(r'^words/success', SuccessView.as_view(), name='words_success'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^words/add/$', WordsAddView.as_view(), name='words_add'),
    url(r'^words/(?P<pk>[0-9]+)/edit/$', WordsEditView.as_view(),
        name='words_edit'),
    url(r'^words/(?P<pk>[0-9]+)/approve/$', WordsApproveView.as_view(),
        name='words_approve'),
]

urlpatterns += [
    url(r'^students/add/$', StudentsAddView.as_view(), name='students_add'),
]

src/padakosham/urls.py
from django.contrib import admin

from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"data/", include('institutions.urls')),
    url(r'^', include('public_pages.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^ui_test/', include('ui_test.urls')),
    url(r'^dashboard/', include('core.urls')),
]

urlpatterns += [
    url(r'^home/', include('core.urls', namespace='home')),
]

src/core/models.py
from django.db import models
from django.conf import settings

from utils.models import TimestampedBaseModel


User = settings.AUTH_USER_MODEL


class Category(models.Model):
    """
    Categories of words like adjective, noun, etc.
    """
    name = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % self.name


class Language(models.Model):
    """
    The language code and its human readable form.
    """
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % self.name


class Place(models.Model):
    """
    Places info.
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return '%s' % self.name


class Word(TimestampedBaseModel):
    """
    Master table for the word text and related metadata.
    """
    text = models.CharField(max_length=50, verbose_name='വാക്ക്')
    etymology = models.TextField(null=True, blank=True,verbose_name='നിഷ്പത്തി')
    homonyms = models.ManyToManyField(
        'self',
        blank=True,
        related_name='homonyms',
        verbose_name='നാനാർത്ഥം'
    )
    is_dialect = models.BooleanField(default=False,verbose_name='പ്രാദേശികഭേദമാണോ?')
    origin_language = models.ForeignKey(Language, null=True, blank=True,related_name='originated_words',verbose_name='ഏതുഭാഷയിൽ നിന്നും വന്നു?')
    language = models.ForeignKey(Language, null=True, blank=True,verbose_name='ഭാഷ')
    place = models.ForeignKey(
        Place,
        null=True,
        blank=True,
        related_name="places",
        verbose_name='പ്രദേശം'
    )
    is_plural = models.BooleanField(default=False,verbose_name='ബഹുവചനമാണോ?')
    plural = models.OneToOneField(
        'self',
        null=True,
        blank=True,
        related_name='plural_of',
        verbose_name='ബഹുവചനം'
    )
    root = models.ForeignKey(
        'self', null=True, blank=True, related_name='derived_words', verbose_name='മൂലപദം')
    singular = models.OneToOneField(
        'self', null=True, blank=True, related_name='singular_of',verbose_name='ഏകവചനം')

    def __str__(self):
        return '%s' % self.text


class WordDetails(TimestampedBaseModel):
    """
    Contains info about Word entry and manipulation.
    """
    word = models.OneToOneField(Word)
    created_by = models.ForeignKey(User, related_name="words_created")
    is_verified = models.BooleanField(default=False)
    verified_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name="words_verified"
    )
class Meaning(models.Model):
    MASCULINE = 'M'
    FEMININE = 'F'
    NEUTRAL = 'N'
    GENDER_CHOICES = (
        (MASCULINE, 'പുല്ലിംഗം',),
        (FEMININE,'സ്ത്രീലിംഗം ',),
        (NEUTRAL, 'നപുംസകലിംഗം',),
    )
    word = models.ForeignKey(Word)
    text = models.TextField(
        verbose_name='അർത്ഥം'
    )
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        default=NEUTRAL,
        verbose_name='ലിംഗം')
    category = models.ForeignKey(
        Category,
        null=True,
        blank=True,
        verbose_name='പദവിഭാഗം'
    )
    examples = models.TextField(null=True, blank=True,verbose_name='ഉദാഹരണം')
    synonyms = models.ManyToManyField(
        Word,
        blank=True,
        related_name="synonyms",
        verbose_name='പര്യായങ്ങൾ'
    )
    opposites = models.ManyToManyField(
        Word,
        blank=True,
        related_name='opposites',
        verbose_name='വിപരീതം'
    )
    # translation = models.ManyToManyField(
    #     'self',
    #     blank=True,
    #     related_name="translations",
    #     verbose_name='പരിഭാഷകൾ'
    # )

    def __str__(self):
        return '%s' % self.text

src/core/forms.py
from django import forms
from crispy_forms.helper import FormHelper

from .models import Word, Meaning


class WordAddForm(forms.ModelForm):

    
    class Meta:
    	model = Word
    	fields = [
        'text', 'etymology', 'homonyms', 'origin_language',
        'place', 'plural', 'singular', 'root',]

    def __init__(self, *args, **kwargs):
        super(WordAddForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.fields['homonyms'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്കിന്റെ വിവിധ അർത്ഥങ്ങൾ കോമ ഉപയോഗിച്ച് വേർതിരിച്ച്  ചേർക്കുക'}
        )
        self.fields['place'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്ക് ഒരു പ്രാദേശികഭേദമാണെങ്കിൽ മാത്രം ഏതു പ്രദേശത്താണ്  പ്രചാരത്തിലുള്ളത് എന്ന് ചേർക്കുക'}
        )
        self.fields['plural'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്കിന്റെ ബഹുവചനം എന്താണ്?'}
        )
        self.fields['singular'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്കിന്റെ ഏകവചനം എന്താണ്?'}
        )
        self.fields['root'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്കിന്റെ മൂലപദം എന്തെന്ന് കണ്ടെത്തി ചേർക്കുക'}
        )

class WordMeaningAddForm(forms.ModelForm):

    class Meta:
        model = Meaning
        fields = [
            'text', 'gender', 'category',
            'examples', 'synonyms', 'opposites',

        ]

    def __init__(self, *args, **kwargs):
        super(WordMeaningAddForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.fields['synonyms'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്കിന്റെ വിവിധ പര്യായങ്ങൾ കോമ ഉപയോഗിച്ച് വേർതിരിച്ച്  ചേർക്കുക'}
        )
        self.fields['opposites'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ ചേർക്കുന്ന അർത്ഥത്തിന്റെ വിപരീതാർത്ഥം വരുന്ന വാക്ക് ചേ‌‌ർക്കുക'}
        )

class StudentAddForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    grade = forms.CharField(label='Your name', max_length=100)
    school =  forms.CharField(label='Your name', max_length=100)

src/core/views.py
from django.views import View
from django.views.generic import FormView, TemplateView
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import WordAddForm, StudentAddForm, WordMeaningAddForm
from .models import Word

class HomeView(TemplateView):
    template_name = 'apps/UI_test/home.html'

class WordsReviewView(View):
    def get(self, request):
        unverified_words = Word.objects.filter(worddetails__is_verified=False)
        context = {
            'unverified_words': unverified_words
        }
        return render(request, "apps/core/review.html", context=context)

class SuccessView(View):
    def get(self, request):
        unverified_words = Word.objects.filter(worddetails__is_verified=False)
        context = {
            'unverified_words': unverified_words
        }
        return render(request, "apps/core/result.html", context=context)

class WordsEditView(View):
    def get(self, request, pk):
        return HttpResponse("LOL!")


class WordsApproveView(View):
    def post(self, request, pk):
        word = Word.objects.get(id=pk)
        word.worddetails.is_verified = True
        word.worddetails.verified_by = request.user
        word.worddetails.save()
        return redirect('review')


class StudentsAddView(FormView):
    template_name = 'apps/core/students_add.html'
    form_class = StudentAddForm

    def post(self, *args, **kwargs):
        return redirect('/home/words/add/')


class WordsAddView(FormView):
    template_name = 'apps/core/words_add.html'
    form_class = WordAddForm

    def form_valid(self, form):
        add_another = self.request.POST.get('add_another')
        finish = self.request.POST.get('finish')

        if finish:
            return redirect('/home/words/success/')
        else:
            return redirect('/home/words/add/')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['form_meaning'] = WordMeaningAddForm
        return context

src/templates/apps/core/result.html
{% include "common/inner_pages.html" %}
<div class="wrapper">
  <div class="row">
    <div class="column col-lg-12 col-md-12 col-sm-12 col-xs-12" id="main">
      <div class="center">
		<div class="hmain">
			<h1 class="hcs" >Thank you!</h1>
			<h2></h2>
		</div>
		<p class="p">വാക്കുകൾ ചേർത്ത് നിങ്ങൾ ഈ സംരംഭത്തിന്റെ ഭാഗമായിരിക്കുന്നു.</p><p class="p">  മലയാളം കമ്പ്യൂട്ടിങ്ങിനുള്ള നിങ്ങളുടെ സംഭാവനകൾ വിലമതിക്കാനാവാത്തതാണ്.</p>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
      <br><br><br>
        <a class="btn btn-default btn-block" href="{% url 'home:home' %}">
          Go back to home
        </a>
      </div>
    </div>
	</div>
    </div>
    <div class="hidden column col-lg-3 col-md-3 col-sm-3 col-xs-12" id="sidebar">
      {% include "common/sidebar.html" %}
    </div>
  </div>
</div>

src/templates/apps/core/review.html
{% for word in unverified_words %}
    Word: {{ word.text }} <br>
    Meanings: <br>
    {% for meaning in word.meaning_set.all %}
      - {{ meaning.text }} <br>
    {% endfor %}
    <form action="{% url 'approve_word' pk=word.id %}" method="POST">{% csrf_token %} 
      <button type="submit" class="btn btn-success btn-lg white">Approve</button>
    </form>
    <a href="{% url 'edit_word' pk=word.id %}"><button type="submit" class="btn btn-success btn-lg white">Edit</button></a>
    <br> <br>
{% endfor %}

src/templates/apps/core/students_add.html
{% include "common/inner_pages.html" %}
<div class="wrapper">
  <div class="row">
    <div class="column col-lg-12 col-md-12 col-sm-12 col-xs-12" id="main">
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="col-lg-12 top-pad100">
              <h2 class="animated zoomIn white">പദകോശം</h2>
              <h4 class="white">നിങ്ങളുടെ വിവരങ്ങൾ ചേർക്കുക</h4>
              <form method='post'>
                {% csrf_token %}
                <div class="form-group animated bounceInLeft">
                  <input type="text" class="form-control" id="student_name" name="name" placeholder="പേര്" required='required'>
                </div>
                <div class="form-group animated bounceInRight">
                  <input type="text" class="form-control" id="grade" name="grade" placeholder="ക്ലാസ്" required='required'>
                </div>
                <div class="form-group animated bounceInLeft">
                  <select class="form-control" id="district" onchange="loadData('subdistrict','/data/retrieve?district='+this.value, 'സബ്‌‌ജില്ല')">
                    <option value="" disabled selected>ജില്ല</option>
                  </select>
                </div>
                <div class="form-group animated bounceInRight">
                  <select class="form-control" id="subdistrict" onchange="loadData('school','/data/retrieve?subdistrict='+this.value, 'സ്കൂൾ')">
                    <option value="" disabled selected>സബ്‌‌ജില്ല</option>
                  </select>
                </div>
                <div class="form-group animated bounceInLeft">
                  <select class="form-control" id="school" name="school1221">
                    <option value="" disabled selected>സ്കൂൾ</option>
                  </select>
                </div>
                  <button type="submit" class="btn btn-success white pull-right">വാക്കുകൾ ചേർത്ത് തുടങ്ങുക </button>
               </form>
            </div>
          </div>
      </div>
    </div>
    <div class="hidden column col-lg-3 col-md-3 col-sm-3 col-xs-12" id="sidebar">
      {% include "common/sidebar.html" %}
    </div>
  </div>
</div>

<script type="text/javascript">

$(function(){
  loadData('district', '/data/retrieve?', 'ജില്ല');
});

function loadData(id, url , option) {
    $("#"+id).html($('<option>', { 
        value   : option,
        text    : option,
        disabled: true,
        selected: true
    }));
    $.ajax({
      type: "GET",
      crossDomain: true,
      url: url,
      dataType: "json",
      success: function(resultData){
          $.each(resultData[Object.keys(resultData)[0]], function (i, item) {
              $("#"+id).append($('<option>', { 
                  value: item,
                  text : item 
              }));
          });
      },
      error: function(e) {
        alert('Check the Console to see Error Messages');
        console.log(e);
      },
    });
};

</script>

src/templates/apps/core/words_add.html
{% load crispy_forms_tags %}

{% include "common/inner_pages.html" %}
<div class="wrapper">
  <div class="row">
    <div class="column col-lg-12 col-md-12 col-sm-12 col-xs-12" id="">
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="col-lg-12 top-pad100">
              <h1 class="animated zoomIn">പദകോശം</h1>

              <h3>ഒരു പുതിയ വാക്ക് ചേർക്കാം</h3>
              <hr>
              <form method='post'>
                {% csrf_token %}
                <div class="tc-word-form">
                  {{ form.text|as_crispy_field }}
                  {{ form_meaning.text|as_crispy_field }}
                </div>
                <hr>
                <div class="tc-meaning-form-wrap">
                  <div class="tc-meaning-form">
                    {{ form_meaning.category|as_crispy_field }}
                    {{ form_meaning.gender|as_crispy_field }}
                    {{ form_meaning.examples|as_crispy_field }}
                    {{ form_meaning.synonyms|as_crispy_field }}
                    {{ form_meaning.opposites|as_crispy_field }}
                    <hr>
                    {{ form.etymology|as_crispy_field }}
                  {{ form.homonyms|as_crispy_field }}
                  {{ form.origin_language|as_crispy_field }}
                  {{ form.place|as_crispy_field }}
                  {{ form.plural|as_crispy_field }}
                  {{ form.singular|as_crispy_field }}
                  {{ form.root|as_crispy_field }}
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4 col-md-offset-4">
                    <input class="btn btn-default btn-block" type="submit" name="add_another" value='മറ്റൊരു വാക്കു കൂടി ചേർക്കുക'>
                  </div>
                  <div class="col-md-4">
                    <input class="btn btn-primary btn-block" type="submit" name="finish" value='വാക്കുകൾ എല്ലാം ചേർത്ത് കഴിഞ്ഞ് ഇവിടെ ക്ലിക്ക് ചെയ്യുക'>
                  </div>
                </div>
                <br><br><br>
              </form>
            </div>
          </div>
      </div>
    </div>
    <div class="hidden column col-lg-3 col-md-3 col-sm-3 col-xs-12" id="sidebar">
      {% include "common/sidebar.html" %}
    </div>
  </div>
</div>

<script type="text/javascript">

$(function(){
  loadData('district', '/data/retrieve?', 'District');
});

function loadData(id, url , option) {
    $("#"+id).html($('<option>', { 
        value   : option,
        text    : option,
        disabled: true,
        selected: true
    }));
    $.ajax({
      type: "GET",
      crossDomain: true,
      url: url,
      dataType: "json",
      success: function(resultData){
          $.each(resultData[Object.keys(resultData)[0]], function (i, item) {
              $("#"+id).append($('<option>', { 
                  value: item,
                  text : item 
              }));
          });
      },
      error: function(e) {
        alert('Check the Console to see Error Messages');
        console.log(e);
      },
    });
};

</script>